services:
  passwordmanager-backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - passwordmanager-network

  jenkins:
    build:
      context: .
      dockerfile: DockerfileJenkins
    hostname: jenkins
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube/config:/root/.kube/config
      - ~/.minikube:/root/.minikube

  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - passwordmanager-network

networks:
  passwordmanager-network:
    driver: bridge

volumes:
  jenkins-data:
  redis-data:
