apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-manager
  template:
    metadata:
      labels:
        app: password-manager
    spec:
      containers:
        - name: password-manager
          image: gourav094/password-manager:latest  
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: password-manager-service
spec:
  selector:
    app: password-manager
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort  # Change to LoadBalancer if deploying to cloud
